nombre = input("Cual es tu nombre? ")
print(nombre)
nombre = nombre.upper()
print(nombre)
nombre = nombre.capitalize()
print(nombre)
nombre = nombre.strip()
print(nombre)
nombre = nombre.lower()
print(nombre)
nombre = nombre.replace("a", "e")
print(nombre)
print(nombre[0])
print(nombre[1])
print(nombre[2])
print(nombre[3])
print(len(nombre))
print(len(nombre[0:2]))
print(nombre[0:2])
print(nombre[0:1:2])
print(nombre[::-1])

